services:

  mongo:
    build: ./mongo
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example

    ports:
      - "27017:27017"

volumes:
  db-data:
